### PR TITLE
feat: remove next token param from list caches

### LINKED ISSUE #382: remove next token from list caches arguments

### PR DESCRIPTION
**Pull request by malandis**
Pending server side support, we remove the next token param from the
list caches control operation.

Closes #382

### CODE REVIEW

**Comment by cprice404** [comment]
> Note: though we remove the argument from the API, we leave next token in the response class.

I actually took this out in node.js in my current PR.  thoughts?

**Review by nand4011 — COMMENTED** [review]
Are we leaving the token in the response object for backwards compatibility? The intention in the node library is to hide the token entirely from the user and handle the paging automatically once it is implemented.

**Comment by malandis** [comment]
> > Note: though we remove the argument from the API, we leave next token in the response class.
> 
> I actually took this out in node.js in my current PR. thoughts?

No strong thoughts. Perhaps an unused field is more confusing than just removing it. I was going to keep it for backwards compatibility since this part of the API was already 1.0

**Comment by cprice404** [comment]
> > > Note: though we remove the argument from the API, we leave next token in the response class.
> > 
> > 
> > I actually took this out in node.js in my current PR. thoughts?
> 
> No strong thoughts. Perhaps an unused field is more confusing than just removing it. I was going to keep it for backwards compatibility since this part of the API was already 1.0

we're already changing this signature though.  I think let's just remove it for now.

**Comment by malandis** [comment]
Removed in https://github.com/momentohq/client-sdk-dotnet/pull/385/commits/a7ef870505ecd955861f2126c4683ef6feaf23ba

**Review by nand4011 — APPROVED** [review]

**Review by cprice404 — APPROVED** [review]

**Pull request merged**
